---
services:
    nginx:
        image: nginx:alpine3.19
        ports:
            -   "${WEB_PORT}:80"
        hostname: nginx
        container_name: test_nginx
        depends_on:
            - php
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./app/public:/app/public"
        logging:
            driver: "local"

    php:
        build:
            context: etc/php
            dockerfile: Dockerfile
        hostname: php
        container_name: test_php
        working_dir: "/app"
        volumes:
            - "./app:/app"
            - "./etc/php/php.ini:/usr/local/etc/php/php.ini:ro"
            - "./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro"
            - "./etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro"
        depends_on:
            - redis
            - db
        logging:
            driver: "local"

    redis:
        image: redis:7.2-alpine3.19
        hostname: redis-db
        container_name: test_redis
        command: "redis-server /usr/local/etc/redis/redis.conf"
        volumes:
            - "./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf"
        logging:
            driver: "local"

    db:
        image: "percona:8-centos"
        hostname: "my-db"
        container_name: "test_db"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
            MYSQL_DATABASE: "${DB_NAME}"
        volumes:
            - ./etc/percona/docker.cnf:/etc/my.cnf.d/docker.cnf:ro
            - ./etc/percona/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        logging:
            driver: "local"
