---
services:
    nginx:
        image: nginx:alpine3.19
        hostname: nginx
        container_name: test_nginx
#        volumes:
#            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
#            - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
        logging:
            driver: "none"

    php:
        build:
            context: etc/php
            dockerfile: Dockerfile
        hostname: php
        container_name: test_php
        working_dir: "/app"
        volumes:
            - ".:/app"
            - "./etc/php/php.ini:/usr/local/etc/php/php.ini:ro"
            - "./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro"
            - "./etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro"
        depends_on:
            - redis
        logging:
            driver: "none"

    redis:
        image: redis:7.2-alpine3.19
        hostname: redis-db
        container_name: test_redis
        logging:
            driver: "none"
